/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.text.DecimalFormat;
import java.text.NumberFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author monocat-maria <github.com/monocat-maria>
 */
public class GastoCalorico extends javax.swing.JFrame {

    /**
     * Creates new form Imc
     */
    public GastoCalorico() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gCContainer = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        containerOutput = new javax.swing.JPanel();
        gastoBasalLabel = new javax.swing.JLabel();
        gastoTotalLabel = new javax.swing.JLabel();
        gastoBasalOutput = new javax.swing.JLabel();
        gastoTotalOutput = new javax.swing.JLabel();
        containerInput = new javax.swing.JPanel();
        pesoLabel = new javax.swing.JLabel();
        alturaLabel = new javax.swing.JLabel();
        pesoInput = new javax.swing.JTextField();
        alturaInput = new javax.swing.JTextField();
        calcularButton = new javax.swing.JButton();
        idadeLabel = new javax.swing.JLabel();
        idadeInput = new javax.swing.JTextField();
        atividadeComboBox = new javax.swing.JComboBox<>();
        atividadeLabel = new javax.swing.JLabel();
        mulherRadioButton = new javax.swing.JRadioButton();
        homemRadioButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(313, 360));
        setPreferredSize(new java.awt.Dimension(313, 360));

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelTitulo.setText("Cálculo de Gasto Calórico");

        containerOutput.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        gastoBasalLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        gastoBasalLabel.setText("Gasto Basal:");

        gastoTotalLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        gastoTotalLabel.setText("Gasto Total:");

        gastoBasalOutput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        gastoTotalOutput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout containerOutputLayout = new javax.swing.GroupLayout(containerOutput);
        containerOutput.setLayout(containerOutputLayout);
        containerOutputLayout.setHorizontalGroup(
            containerOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerOutputLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(containerOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerOutputLayout.createSequentialGroup()
                        .addComponent(gastoBasalLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gastoBasalOutput, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                    .addGroup(containerOutputLayout.createSequentialGroup()
                        .addComponent(gastoTotalLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gastoTotalOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        containerOutputLayout.setVerticalGroup(
            containerOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerOutputLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gastoBasalLabel)
                    .addComponent(gastoBasalOutput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gastoTotalOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gastoTotalLabel))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        containerInput.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pesoLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pesoLabel.setText("Peso (Kg)");

        alturaLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        alturaLabel.setText("Altura (cm):");

        pesoInput.setMinimumSize(new java.awt.Dimension(64, 30));
        pesoInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesoInputActionPerformed(evt);
            }
        });

        alturaInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alturaInputActionPerformed(evt);
            }
        });

        calcularButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        calcularButton.setText("Calcular");
        calcularButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularButtonActionPerformed(evt);
            }
        });

        idadeLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        idadeLabel.setText("Idade:");

        idadeInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idadeInputActionPerformed(evt);
            }
        });

        atividadeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sedentário", "Leve", "Moderado", "Ativo", "Extremamente Ativo" }));
        atividadeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atividadeComboBoxActionPerformed(evt);
            }
        });

        atividadeLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        atividadeLabel.setText("Nível de Atividade");

        mulherRadioButton.setText("Mulher");
        mulherRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulherRadioButtonActionPerformed(evt);
            }
        });

        homemRadioButton.setText("Homem");
        homemRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homemRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout containerInputLayout = new javax.swing.GroupLayout(containerInput);
        containerInput.setLayout(containerInputLayout);
        containerInputLayout.setHorizontalGroup(
            containerInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(containerInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerInputLayout.createSequentialGroup()
                        .addGroup(containerInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(containerInputLayout.createSequentialGroup()
                                .addComponent(mulherRadioButton)
                                .addGap(43, 43, 43)
                                .addComponent(homemRadioButton))
                            .addGroup(containerInputLayout.createSequentialGroup()
                                .addGroup(containerInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pesoLabel)
                                    .addComponent(alturaLabel)
                                    .addComponent(idadeLabel))
                                .addGap(34, 34, 34)
                                .addGroup(containerInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pesoInput, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                    .addComponent(alturaInput)
                                    .addComponent(idadeInput))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerInputLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(containerInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(calcularButton)
                            .addGroup(containerInputLayout.createSequentialGroup()
                                .addComponent(atividadeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(atividadeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(157, 157, 157))))
        );
        containerInputLayout.setVerticalGroup(
            containerInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mulherRadioButton)
                    .addComponent(homemRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alturaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alturaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idadeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idadeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atividadeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atividadeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calcularButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout gCContainerLayout = new javax.swing.GroupLayout(gCContainer);
        gCContainer.setLayout(gCContainerLayout);
        gCContainerLayout.setHorizontalGroup(
            gCContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gCContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gCContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(containerOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTitulo)
                    .addComponent(containerInput, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        gCContainerLayout.setVerticalGroup(
            gCContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gCContainerLayout.createSequentialGroup()
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(containerInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(containerOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gCContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gCContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alturaInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alturaInputActionPerformed

    }//GEN-LAST:event_alturaInputActionPerformed

    private void calcularButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularButtonActionPerformed
        if(!mulherRadioButton.isSelected() && !homemRadioButton.isSelected()){
            JOptionPane.showMessageDialog(rootPane, "Selecione um gênero.");
        }else{
            calcularGastoCalorico();
        }   
    }//GEN-LAST:event_calcularButtonActionPerformed

    private void pesoInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesoInputActionPerformed
        
    }//GEN-LAST:event_pesoInputActionPerformed

    private void idadeInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idadeInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idadeInputActionPerformed

    private void mulherRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mulherRadioButtonActionPerformed
        mulherRadioButton.setSelected(true);
        homemRadioButton.setSelected(false);
    }//GEN-LAST:event_mulherRadioButtonActionPerformed

    private void homemRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homemRadioButtonActionPerformed
        mulherRadioButton.setSelected(false);
        homemRadioButton.setSelected(true);
    }//GEN-LAST:event_homemRadioButtonActionPerformed

    private void atividadeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atividadeComboBoxActionPerformed
       
    }//GEN-LAST:event_atividadeComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GastoCalorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GastoCalorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GastoCalorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GastoCalorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GastoCalorico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alturaInput;
    private javax.swing.JLabel alturaLabel;
    private javax.swing.JComboBox<String> atividadeComboBox;
    private javax.swing.JLabel atividadeLabel;
    private javax.swing.JButton calcularButton;
    private javax.swing.JPanel containerInput;
    private javax.swing.JPanel containerOutput;
    private javax.swing.JPanel gCContainer;
    private javax.swing.JLabel gastoBasalLabel;
    private javax.swing.JLabel gastoBasalOutput;
    private javax.swing.JLabel gastoTotalLabel;
    private javax.swing.JLabel gastoTotalOutput;
    private javax.swing.JRadioButton homemRadioButton;
    private javax.swing.JTextField idadeInput;
    private javax.swing.JLabel idadeLabel;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JRadioButton mulherRadioButton;
    private javax.swing.JTextField pesoInput;
    private javax.swing.JLabel pesoLabel;
    // End of variables declaration//GEN-END:variables
    
    public void calcularImc(){
        double altura = Double.parseDouble(pesoInput.getText());
        double peso = Double.parseDouble(alturaInput.getText());
        
        double imc = peso / (altura * altura);
        NumberFormat imcDouble = new DecimalFormat(".#");
        imcDouble.format(imc);
        
            if(imc < 18.5){
            gastoBasalOutput.setText(imcDouble.format(imc));
            gastoTotalOutput.setText("Magreza");
        }else if(imc < 24.9){
            gastoBasalOutput.setText(imcDouble.format(imc));
            gastoTotalOutput.setText("Normal");
        }else if(imc < 29.9){
            gastoBasalOutput.setText(imcDouble.format(imc));
            gastoTotalOutput.setText("Sobrepeso");
        }else if(imc < 30){
            gastoBasalOutput.setText(imcDouble.format(imc));
            gastoTotalOutput.setText("Obesidade");
        }else{    
            gastoBasalOutput.setText(imcDouble.format(imc));
            gastoTotalOutput.setText("Obesidade grave");
        }     
    }
    
    public void calcularGastoCalorico(){
        double altura = Double.parseDouble(alturaInput.getText());
        double peso = Double.parseDouble(pesoInput.getText());
        double idade = Double.parseDouble(idadeInput.getText());
        
        double calBasal = 0;
        
        if(homemRadioButton.isSelected()){
            calBasal = 66 + (13.8 * peso) + (5 * altura) - (6.8 * idade);
        }else if(mulherRadioButton.isSelected()){
            calBasal = 665 + (9.6 * peso) + (1.9 * altura) - (4.7 * idade);
        }
        
        double calTotal = 0;
        
        switch (atividadeComboBox.getSelectedIndex()) {
            case 0 -> calTotal = calBasal * 1.2;
            case 1 -> calTotal = calBasal * 1.375;
            case 2 -> calTotal = calBasal * 1.55;
            case 3 -> calTotal = calBasal * 1.725;
            case 4 -> calTotal = calBasal * 1.9;
            default -> JOptionPane.showMessageDialog(rootPane, "Selecione uma atividade.");
        }
        
        
        String basalOutput = Double.toString(calBasal);
        gastoBasalOutput.setText(basalOutput);
        
        
        String totalOutput = Double.toString(calTotal);
        gastoTotalOutput.setText(totalOutput);
    }
}

